name = "scarabev-market-worker"
main = "worker.js"
compatibility_date = "2026-03-13"
compatibility_flags = ["global_fetch_strictly_public"]
workers_dev = true

[[kv_namespaces]]
binding = "EV_HISTORY"
id = "45058621c81d439d9ce0d12b61dc0c66"

[[services]]
binding = "SCARABEV_API"
service = "scarabev-api"

[triggers]
crons = ["*/5 * * * *", "0 18 * * *"]
