// Auto-generated from admin-ui-src/scripts/base.js. Do not edit this file directly.
export const ADMIN_BASE_SCRIPT = String.raw`

const THEME_KEY='scarabev-admin-theme';
const MAIN_THEME_KEY='poepool-theme';
const WS_PROFILES_KEY='scarabev-admin-workspace-profiles-v2';
const WS_ACTIVE_KEY='scarabev-admin-workspace-active-v2';
const WS_SELECTED_KEY='scarabev-admin-workspace-selected-v2';
const SESS_CFG_KEY='scarabev-admin-session-manager-v1';
const HEALTH_CARD_LAYOUT_KEY='scarabev-admin-health-card-layout-v1';
const HEALTH_OPEN_CARDS_KEY='scarabev-admin-health-open-cards-v1';

const state={
  user:null,scarabs:[],filtered:[],selected:null,selectedId:null,creating:false,
  tokensByName:{},draftTokensByScarabId:{},latestDraftEntries:[],sets:[],selectedIds:new Set(),
  sortBy:'name_asc',activePanel:'scarab',workspaceProfiles:[],activeWorkspaceId:null,selectedWorkspaceId:null,
  captureQueue:[],sessionApiUrl:'',sessionAdminKey:'',sessions:[],sessionExpandedIds:new Set(),sessionReviewExpandedIds:new Set(),sessionSelectedIds:new Set(),sessionRecentRerunIds:new Set(),sessionRecentChangedIds:new Set(),sessionLastRerunSummary:'',sessionHealthScope:'aggregate',sessionPageSize:25,sessionPage:1,sessionsAutoLoaded:false,backupsAutoLoaded:false,scarabsAutoLoaded:false,tokensAutoLoaded:false,healthAutoLoaded:false,bulkToolsAutoLoaded:false,
  sessionDupes:[],sessionSignals:[],sessionReviewQueue:[],sessionResearchPile:[],sessionIntakeAnalytics:null,healthCardLayout:null,healthLastResults:null,healthDragId:null,healthDragPlaceholder:null,healthOpenCards:{},healthOpenLoaded:false,
  failureLogsAutoLoaded:false,failureLogs:[],manualRetryBusy:false
};

const $=(id)=>document.getElementById(id);
const status=(id,msg,t)=>{const n=$(id);if(!n)return;n.className='status'+(t?(' '+t):'');n.textContent=msg;};
const toast=(m)=>{const t=$('toast');t.textContent=m;t.style.display='block';clearTimeout(window.__tt);window.__tt=setTimeout(()=>t.style.display='none',2200);};
const busy=(id,b)=>{const x=$(id);if(!x)return;x.disabled=!!b;if(b){x.dataset.prev=x.textContent;x.textContent='Working...';}else if(x.dataset.prev){x.textContent=x.dataset.prev;}};
function clipText(v,maxLen){
  const s=String(v||'').replace(/\\s+/g,' ').trim();
  if(!s)return '';
  const n=Number(maxLen)||160;
  return s.length>n?(s.slice(0,n)+'...'):s;
}
function formatApiFailure(res,json,text){
  const statusCode=res&&typeof res.status==='number'?res.status:0;
  const jsonMsg=(json&&typeof json==='object')
    ?(json.errorDetail||json.error||json.message||json.detail||json.reason||'')
    :'';
  const body=clipText(jsonMsg||text||'',180);
  return 'HTTP '+statusCode+(body?(': '+body):'');
}
function formatThrownError(err){
  const msg=(err&&err.message)?err.message:String(err||'error');
  return clipText(msg,180)||'error';
}

function formatAdminTime(value){
  if(!value)return '-';
  const d=new Date(value);
  if(Number.isNaN(d.getTime()))return String(value);
  const parts=new Intl.DateTimeFormat('en-CA',{
    timeZone:'America/Los_Angeles',
    year:'numeric',
    month:'2-digit',
    day:'2-digit',
    hour:'2-digit',
    minute:'2-digit',
    hour12:false
  }).formatToParts(d);
  const pick=(type)=>parts.find((p)=>p.type===type)?.value||'00';
  return pick('year')+'-'+pick('month')+'-'+pick('day')+' '+pick('hour')+':'+pick('minute');
}

function applyTheme(t){document.documentElement.setAttribute('data-theme',t==='light'?'light':'dark');$('themeBtn').textContent=t==='light'?'Theme: Light':'Theme: Dark';}
function initTheme(){let t='dark';try{const own=localStorage.getItem(THEME_KEY),shared=localStorage.getItem(MAIN_THEME_KEY);if(own==='light'||own==='dark')t=own;else if(shared==='light'||shared==='dark')t=shared;}catch(e){}applyTheme(t);}
function toggleTheme(){const dark=document.documentElement.getAttribute('data-theme')!=='light';const n=dark?'light':'dark';try{localStorage.setItem(THEME_KEY,n);localStorage.setItem(MAIN_THEME_KEY,n);}catch(e){}applyTheme(n);}

function switchPanel(name){
  state.activePanel=name;
  const labels={scarab:'Scarab Manager',sessions:'Session Manager',health:'Health',failures:'Failure Logs',bulktools:'Bulk Tools',regex:'Regex Lab',recomb:'Recombinator Lab'};
  ['scarab','sessions','health','failures','bulktools','regex','recomb'].forEach((n)=>{const p=$('panel-'+n);if(p)p.classList.toggle('active',n===name);});
  document.querySelectorAll('.navbtn').forEach((b)=>b.classList.toggle('active',b.dataset.panel===name));
  $('panelTitle').textContent=(labels[name]||'Dashboard')+' | Staging-first control plane';
  closeMobileNav();
}

function isMobileNav(){return !!window.matchMedia&&window.matchMedia('(max-width:1000px)').matches;}
function setMobileNavOpen(open){
  const app=$('app');const btn=$('navToggleBtn');if(!app)return;
  app.classList.toggle('nav-open',!!open);
  if(btn)btn.setAttribute('aria-expanded',open?'true':'false');
}
function toggleMobileNav(){if(!isMobileNav())return;const app=$('app');if(!app)return;setMobileNavOpen(!app.classList.contains('nav-open'));}
function closeMobileNav(){if(!isMobileNav())return;setMobileNavOpen(false);}

function setAuthUi(ok){$('login').classList.toggle('hidden',ok);$('app').classList.toggle('hidden',!ok);$('topBar').classList.toggle('hidden',!ok);$('sessionTxt').textContent=ok?('Signed in: '+state.user.username):'Signed out';if(ok)closeMobileNav();}
function csrf(){const p=document.cookie.split(';').map((v)=>v.trim()).find((v)=>v.startsWith('scarabev_csrf='));return p?decodeURIComponent(p.slice(14)):'';}
async function api(path,opt={}){
  const m=opt.method||'GET';
  const h=opt.headers||{};
  if(opt.body&&!h['content-type'])h['content-type']='application/json';
  if(m!=='GET'&&m!=='HEAD')h['x-csrf-token']=csrf();
  const timeoutMs=Number(opt.timeoutMs);
  const useTimeout=Number.isFinite(timeoutMs)&&timeoutMs>0;
  const ctl=(useTimeout&&typeof AbortController!=='undefined')?new AbortController():null;
  let timer=null;
  if(ctl){
    timer=setTimeout(()=>{try{ctl.abort();}catch(e){}},Math.max(500,Math.floor(timeoutMs)));
  }
  try{
    const r=await fetch(path,{method:m,headers:h,body:opt.body,credentials:'include',signal:ctl?ctl.signal:undefined});
    const txt=await r.text();
    let j=null;try{j=JSON.parse(txt);}catch(e){}
    return{res:r,json:j,text:txt};
  }catch(e){
    const msg=String((e&&e.message)||e||'request_failed');
    return{res:{status:0,ok:false},json:null,text:msg};
  }finally{
    if(timer)clearTimeout(timer);
  }
}

function badge(s){const c=s==='active'?'active':(s==='retired'?'retired':'draft');return '<span class="badge '+c+'">'+s+'</span>';}
function escRegex(s){return String(s).replace(/[.*+?^{}()|[\\]\\$]/g,'\\$&');}
function modArr(v){return v.split(/\\r?\\n|,/).map((x)=>x.trim()).filter(Boolean);}

`;
