// Auto-generated from admin-ui-src/scripts/failures.js. Do not edit this file directly.
export const ADMIN_FAILURES_SCRIPT = String.raw`
function setManualRetryBusy(buttonEl,isBusy,label){
  const btn=(buttonEl&&typeof buttonEl==='object')?buttonEl:null;
  if(!btn)return;
  if(isBusy){
    btn.disabled=true;
    btn.dataset.prevText=btn.textContent||'';
    const lower=String(label||'').toLowerCase();
    btn.textContent=lower.includes('retry')?'Retrying...':'Refreshing...';
    return;
  }
  btn.disabled=false;
  if(btn.dataset.prevText){
    btn.textContent=btn.dataset.prevText;
    delete btn.dataset.prevText;
  }
}

function failureEsc(v){
  if(typeof escHtml==='function')return escHtml(String(v==null?'':v));
  return String(v==null?'':v)
    .replace(/&/g,'&amp;')
    .replace(/</g,'&lt;')
    .replace(/>/g,'&gt;')
    .replace(/\"/g,'&quot;')
    .replace(/'/g,'&#39;');
}

function failureFmtTime(value){
  if(!value)return '-';
  try{return formatAdminTime(value);}catch(e){return String(value);} 
}

function failureAttemptsSummary(context){
  const ctx=(context&&typeof context==='object')?context:{};
  const hasCounted=Number.isFinite(Number(ctx.attempts));
  const hasEstimated=Number.isFinite(Number(ctx.estimatedAttempts));
  if(!hasCounted&&!hasEstimated)return '';
  const counted=hasCounted?Math.max(0,Number(ctx.attempts)):null;
  const estimated=hasEstimated?Math.max(0,Number(ctx.estimatedAttempts)):null;
  const source=ctx.attemptsSource?String(ctx.attemptsSource):'unknown';
  const cadence=ctx.retryCadenceLabel?String(ctx.retryCadenceLabel):(Number.isFinite(Number(ctx.retryIntervalMs))?('every '+Math.max(1,Math.round(Number(ctx.retryIntervalMs)/1000))+'s'):'duration');
  const delta=Number.isFinite(Number(ctx.attemptsDelta))?Number(ctx.attemptsDelta):null;
  const parts=[];
  if(counted!=null)parts.push('Counted '+counted+' ('+source+')');
  if(estimated!=null)parts.push('Estimated '+estimated+' ('+cadence+')');
  if(delta!=null)parts.push('Delta '+(delta>=0?'+':'')+delta);
  return parts.join(' | ');
}

function failureOutcome(code,context,severity){
  const c=String(code||'').toLowerCase();
  const recoveredFlag=(context&&typeof context==='object'&&typeof context.recovered==='boolean')?context.recovered:null;
  if(recoveredFlag===true||c.endsWith('_recovered')){
    return {key:'recovered',label:'Recovered',badge:'ok'};
  }
  if(c.endsWith('_exhausted_unresolved')){
    return {key:'unresolved',label:'Unresolved (Exhausted)',badge:'danger'};
  }
  if(c.endsWith('_expired_unresolved')){
    return {key:'unresolved',label:'Unresolved (Expired)',badge:'warn'};
  }
  if(c.endsWith('_corrupt_state_unresolved')){
    return {key:'unresolved',label:'Unresolved (Corrupt State)',badge:'danger'};
  }
  if(c.endsWith('_closed_unresolved')||c.includes('_unresolved')){
    return {key:'unresolved',label:'Unresolved (Closed)',badge:'warn'};
  }
  if(c.endsWith('_failed')){
    const sev=String(severity||'').toLowerCase();
    return {key:'failed',label:'Failed',badge:sev==='warn'?'warn':'danger'};
  }
  const sev=String(severity||'').toLowerCase();
  if(sev==='info')return {key:'info',label:'Info',badge:'ok'};
  if(sev==='warn')return {key:'warn',label:'Warn',badge:'warn'};
  return {key:'error',label:'Error',badge:'danger'};
}

function failureGuidance(code,context){
  const c=String(code||'').toLowerCase();
  const stage=String((context&&context.stage)||'').toLowerCase();
  if(c.endsWith('_recovered')){
    return {
      what:'Incident recovered and service returned to healthy operation.',
      next:'Confirm duration/attempt metrics and watch for repeat incidents on the same subsystem.'
    };
  }
  if(c.endsWith('_exhausted_unresolved')){
    return {
      what:'Incident did not recover and retries were exhausted.',
      next:'Inspect reason/finalError context, then run targeted manual remediation before retriggering.'
    };
  }
  if(c.endsWith('_expired_unresolved')){
    return {
      what:'Incident did not recover before its retry window/date expired.',
      next:'Use reason/cleanup context to determine what was dropped and start a fresh run if still needed.'
    };
  }
  if(c.endsWith('_corrupt_state_unresolved')){
    return {
      what:'Incident closed unresolved due to corrupt state tracking.',
      next:'Inspect cleanup context and reinitialize the flow with a fresh manual run.'
    };
  }
  if(c.endsWith('_closed_unresolved')||c.includes('_unresolved')){
    return {
      what:'Incident closed unresolved without a successful recovery.',
      next:'Review reason/lastError/finalError fields, then run corrective action before retrying.'
    };
  }
  if(c==='snapshot_weights_unavailable'){
    return {
      what:'Could not fetch weighted market inputs needed to compute EV.',
      next:'Check aggregate/weights upstream availability, then retry snapshot.'
    };
  }
  if(c==='snapshot_league_incomplete'){
    return {
      what:'Snapshot wrote only part of the required data for this league.',
      next:'System will retry automatically; use manual retry if it remains incomplete.'
    };
  }
  if(c==='snapshot_harmonic_unavailable'){
    return {
      what:'Harmonic EV could not be computed from the current data.',
      next:'Verify scarab market payload quality and retry.'
    };
  }
  if(c==='snapshot_weighted_unavailable'){
    return {
      what:'Weighted EV calculation failed for this attempt.',
      next:'Check weighted inputs and retry snapshot.'
    };
  }
  if(c==='snapshot_atlas_unavailable'){
    return {
      what:'Atlas EV metrics could not be calculated.',
      next:'Validate atlas inputs/config and retry snapshot.'
    };
  }
  if(c==='snapshot_no_scarab_lines'){
    return {
      what:'No scarab market lines were returned by upstream.',
      next:'Wait for upstream market data to recover, then retry.'
    };
  }
  if(c==='snapshot_retry_exhausted'){
    return {
      what:'Automatic retries reached the max attempts for today.',
      next:'Run a manual retry after upstream data is healthy.'
    };
  }
  if(c==='snapshot_retry_state_corrupt'){
    return {
      what:'Retry tracking state was invalid and was reset.',
      next:'Run a manual retry to rebuild a clean retry state.'
    };
  }
  if(c==='snapshot_retry_expired'){
    return {
      what:'Pending retry state was from a previous day and got expired.',
      next:'Expected after date rollover; today will create fresh snapshot state.'
    };
  }
  if(c==='manual_retry_failed'){
    return {
      what:'A manual retry action failed to complete.',
      next:'Inspect error context and rerun the specific retry action.'
    };
  }
  if(c==='snapshot_exception'){
    return {
      what:'Snapshot process hit an unexpected runtime error.',
      next:'Inspect error details in context and retry after fixing root cause.'
    };
  }
  if(c==='backup_snapshot_failed'){
    return {
      what:'Backend backup snapshot failed before completing coverage/write.',
      next:'Check context error detail, fix root cause, then run backup again.'
    };
  }
  if(c==='backup_snapshot_coverage_missing'){
    return {
      what:'Backup finished but market-worker backup coverage is incomplete.',
      next:'Review missing scopes/total keys in context, then rerun backup after fixing source coverage.'
    };
  }
  if(c==='backup_smoke_failed'){
    return {
      what:'Automated backup smoke restore test failed.',
      next:'Inspect smoke error/source key, fix restore path, then rerun smoke test.'
    };
  }
  if(c==='price_history_backfill_fallback_enabled'){
    return {
      what:'Emergency sparkline backfill fallback was manually enabled.',
      next:'Use only during incidents; monitor logs and disable once normal history writes recover.'
    };
  }
  if(c==='price_history_backfill_fallback_used'){
    return {
      what:'Price history was backfilled from upstream sparkline fallback.',
      next:'Treat as degraded mode; verify normal history writes and disable fallback when stable.'
    };
  }
  if(c==='price_history_backfill_fallback_expired'){
    return {
      what:'Emergency sparkline backfill fallback window expired and was auto-disabled.',
      next:'Confirm history writes are healthy; re-enable only if recovery is still required.'
    };
  }
  if(c==='price_history_backfill_fallback_disabled'){
    return {
      what:'Emergency sparkline backfill fallback was manually disabled.',
      next:'Normal mode restored; continue monitoring history depth for regressions.'
    };
  }
  if(stage==='fetch_weights'){
    return {
      what:'Weighted inputs fetch failed during the weights stage.',
      next:'Check aggregate endpoint health and network/service bindings.'
    };
  }
  return {
    what:'The pipeline encountered an error for this step.',
    next:'Use code + context to pinpoint root cause, then retry.'
  };
}

function renderFailureLogs(events){
  const rowsEl=$('failureRows');
  if(!rowsEl)return;
  const list=Array.isArray(events)?events:[];
  if(!list.length){
    rowsEl.innerHTML='<tr><td colspan="6" class="sub">No operational incident events in selected window.</td></tr>';
    return;
  }
  rowsEl.innerHTML=list.map((evt)=>{
    const at=failureFmtTime(evt&&evt.at?evt.at:null);
    const code=failureEsc((evt&&evt.code)||'unknown_error');
    const src=failureEsc((evt&&evt.source)||'market-worker');
    const msg=failureEsc((evt&&evt.message)||'');
    const sev=String((evt&&evt.severity)||'').toLowerCase();
    const rawCtx=(evt&&evt.context&&typeof evt.context==='object')?evt.context:{};
    const outcome=failureOutcome((evt&&evt.code)||'',rawCtx,sev);
    const outcomeBadge='<span class="badge '+failureEsc(outcome.badge)+'">'+failureEsc(outcome.label)+'</span>';
    const attemptsSummary=failureAttemptsSummary(rawCtx);
    const attemptsLine=attemptsSummary?('<div class="sub">Attempts: '+failureEsc(attemptsSummary)+'</div>'):'';
    const guide=failureGuidance((evt&&evt.code)||'',rawCtx);
    const guideWhat=failureEsc(guide.what);
    const guideNext=failureEsc(guide.next);
    let ctx='{}';
    try{ctx=JSON.stringify(rawCtx,null,0);}catch(e){ctx='{}';}
    return '<tr>'
      +'<td class="mono">'+failureEsc(at)+'</td>'
      +'<td class="mono">'+code+'</td>'
      +'<td class="mono">'+src+'</td>'
      +'<td>'+outcomeBadge+'</td>'
      +'<td><div>'+msg+'</div>'+attemptsLine+'<div class="sub">What happened: '+guideWhat+'</div><div class="sub">Next step: '+guideNext+'</div></td>'
      +'<td class="mono">'+failureEsc(ctx)+'</td>'
      +'</tr>';
  }).join('');
}

async function loadFailureLogs(opts){
  const quiet=!!(opts&&opts.quiet);
  busy('failureRefreshBtn',true);
  try{
    const days=Math.max(1,Math.min(30,Number(($('failureDays')&&$('failureDays').value)||30)||30));
    const r=await api('/admin/ops/failure-logs?days='+days);
    if(r.res.status!==200||!r.json||!r.json.ok){
      const detail=formatApiFailure(r.res,r.json,r.text);
      status('failureStatus','Failed to load logs: '+detail,'err');
      return false;
    }
    const events=Array.isArray(r.json.events)?r.json.events:[];
    state.failureLogs=events;
    renderFailureLogs(events);
    state.failureLogsAutoLoaded=true;
    let recoveredCount=0,unresolvedCount=0,failedCount=0;
    for(const evt of events){
      const ctx=(evt&&evt.context&&typeof evt.context==='object')?evt.context:{};
      const outcome=failureOutcome((evt&&evt.code)||'',ctx,(evt&&evt.severity)||'');
      if(outcome.key==='recovered')recoveredCount++;
      else if(outcome.key==='unresolved')unresolvedCount++;
      else if(outcome.key==='failed')failedCount++;
    }
    const meta='Window '+days+'d | Events '+events.length.toLocaleString()+' | Failed '+failedCount.toLocaleString()+' | Recovered '+recoveredCount.toLocaleString()+' | Unresolved '+unresolvedCount.toLocaleString();
    const metaEl=$('failureMeta');
    if(metaEl)metaEl.textContent=meta;
    const tone=unresolvedCount>0?'err':(failedCount>0?'warn':'ok');
    status('failureStatus','Operational logs refreshed at '+formatAdminTime(new Date().toISOString())+'.',tone);
    return true;
  }catch(e){
    status('failureStatus','Failed to load logs: '+formatThrownError(e),'err');
    return false;
  }finally{
    busy('failureRefreshBtn',false);
  }
}

async function clearFailureLogs(buttonEl){
  if(state.manualRetryBusy)return false;
  const confirmed=window.confirm('Clear failure logs for the last 30 days?');
  if(!confirmed)return false;
  state.manualRetryBusy=true;
  setManualRetryBusy(buttonEl,true,'Clear logs');
  status('failureStatus','Clearing failure logs...','warn');
  try{
    const r=await api('/admin/ops/retry',{
      method:'POST',
      body:JSON.stringify({action:'clear-failure-logs'})
    });
    if(r.res.status!==200||!r.json||!r.json.ok){
      status('failureStatus','Failed to clear logs: '+formatApiFailure(r.res,r.json,r.text),'err');
      return false;
    }
    state.failureLogs=[];
    renderFailureLogs([]);
    const metaEl=$('failureMeta');
    if(metaEl)metaEl.textContent='Window 30d | Events 0';
    status('failureStatus','Failure logs cleared.','ok');
    if(typeof loadHealthOverview==='function'){
      await loadHealthOverview({quiet:true});
    }
    return true;
  }catch(e){
    status('failureStatus','Failed to clear logs: '+formatThrownError(e),'err');
    return false;
  }finally{
    state.manualRetryBusy=false;
    setManualRetryBusy(buttonEl,false,'Clear logs');
  }
}

async function runManualRetryAction(action,label,buttonEl,statusTargetId){
  const target=String(action||'').trim().toLowerCase();
  const statusId=String(statusTargetId||'healthStatus');
  if(!target)return false;
  if(state.manualRetryBusy)return false;
  state.manualRetryBusy=true;
  setManualRetryBusy(buttonEl,true,label||target);
  const startedAt=Date.now();
  status(statusId,'Running '+(label||target)+'...','warn');
  const ticker=setInterval(()=>{
    try{
      const secs=Math.max(0,Math.floor((Date.now()-startedAt)/1000));
      if(buttonEl&&typeof buttonEl==='object')buttonEl.textContent='Running... '+secs+'s';
      status(statusId,'Running '+(label||target)+'... '+secs+'s','warn');
    }catch(e){}
  },1000);
  toast((label||target)+' started');
  try{
    const r=await api('/admin/ops/retry',{
      method:'POST',
      body:JSON.stringify({action:target}),
      timeoutMs:70000
    });
    if(r.res.status===0){
      status(statusId,(label||target)+' timed out or network failed after '+Math.max(1,Math.floor((Date.now()-startedAt)/1000))+'s.','err');
      toast((label||target)+' timed out');
      return false;
    }
    if(r.res.status!==200||!r.json||!r.json.ok){
      status(statusId,'Manual retry failed: '+formatApiFailure(r.res,r.json,r.text),'err');
      toast((label||target)+' failed');
      return false;
    }
    const took=Math.max(0,Number(r.json.elapsedMs)||0);
    status(statusId,(label||target)+' completed in '+took+'ms.','ok');
    toast((label||target)+' completed');
    // Force next health read to bypass short-lived market bundle cache.
    if(typeof marketHealthCacheAt!=='undefined') marketHealthCacheAt=0;
    if(typeof marketHealthCache!=='undefined') marketHealthCache=null;
    if(typeof marketHealthInFlight!=='undefined') marketHealthInFlight=null;
    if(typeof loadHealthOverview==='function'){
      await loadHealthOverview({quiet:true});
    }
    if(state.activePanel==='failures'){
      await loadFailureLogs({quiet:true});
    }
    return true;
  }catch(e){
    status(statusId,'Manual retry failed: '+formatThrownError(e),'err');
    toast((label||target)+' failed');
    return false;
  }finally{
    clearInterval(ticker);
    state.manualRetryBusy=false;
    setManualRetryBusy(buttonEl,false,label||target);
  }
}

async function runSnapshotRetryAction(buttonEl){
  const snap=(state&&state.healthLastResults&&state.healthLastResults.snapshot)||{};
  const telemetry=(snap&&snap.telemetry&&typeof snap.telemetry==='object')?snap.telemetry:{};
  const status=String(telemetry.status||'').toLowerCase();
  const pendingCount=Array.isArray(telemetry.pendingLeagues)?telemetry.pendingLeagues.length:0;
  const shouldRetry=status.includes('retry')||pendingCount>0;
  const action=shouldRetry?'snapshot-retry':'snapshot-run';
  const label=shouldRetry?'Snapshot retry':'Snapshot run';
  return runManualRetryAction(action,label,buttonEl);
}

async function runPriceHistoryBackfillEnable(buttonEl){
  const ok=await runManualRetryAction('price-history-backfill-enable-once','Price history backfill enable',buttonEl,'failureStatus');
  if(ok&&typeof loadFailureLogs==='function'){
    await loadFailureLogs({quiet:true});
  }
  return ok;
}

async function runPriceHistoryBackfillDisable(buttonEl){
  const ok=await runManualRetryAction('price-history-backfill-disable','Price history backfill disable',buttonEl,'failureStatus');
  if(ok&&typeof loadFailureLogs==='function'){
    await loadFailureLogs({quiet:true});
  }
  return ok;
}

`;
