export const ADMIN_REGEX_SCRIPT = String.raw`
function hasRegexOperators(v){return /(^|[^\\])[\[\](){}|+*?]/.test(String(v||''));}
function optimizeWhitespace(v,preferFlexible){const base=String(v||'').trim();if(!base)return base;if(!hasRegexOperators(base))return base.replace(/\s+/g,' ');if(!preferFlexible)return base;return base.replace(/\s+/g,'\\s+');}
function joinAlt(parts){const p=parts.filter((x)=>x!==undefined&&x!==null).map(String).filter(Boolean);if(!p.length)return '';if(p.length===1)return p[0];return '(?:'+p.join('|')+')';}
function charClassFromDigits(chars){const uniq=[...new Set(chars)].sort();if(uniq.length===1)return uniq[0];if(uniq.length===10&&uniq[0]==='0'&&uniq[9]==='9')return '\\d';const ranges=[];let start=uniq[0],prev=uniq[0];for(let i=1;i<uniq.length;i+=1){const c=uniq[i];if(c.charCodeAt(0)===prev.charCodeAt(0)+1){prev=c;continue;}ranges.push(start===prev?start:(start+'-'+prev));start=c;prev=c;}ranges.push(start===prev?start:(start+'-'+prev));return '['+ranges.join('')+']';}
function buildDigitTrie(values){const root={t:false,c:new Map()};for(const v of values){let n=root;for(const ch of String(v)){if(!n.c.has(ch))n.c.set(ch,{t:false,c:new Map()});n=n.c.get(ch);}n.t=true;}return root;}
function trieToRegex(node){const entries=[...node.c.entries()].sort((a,b)=>a[0].localeCompare(b[0]));const byTail=new Map();for(const [digit,child] of entries){const tail=trieToRegex(child);const list=byTail.get(tail)||[];list.push(digit);byTail.set(tail,list);}const parts=[];for(const [tail,digits] of byTail.entries()){const head=charClassFromDigits(digits);parts.push(head+tail);}if(node.t)parts.push('');const nonEmpty=parts.filter(Boolean);if(node.t&&nonEmpty.length===1)return '(?:'+nonEmpty[0]+')?';return joinAlt(parts);}
function compressNumericValues(values){const vals=[...new Set(values.map((v)=>String(v)))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));if(!vals.length)return null;const trie=buildDigitTrie(vals);return trieToRegex(trie)||null;}
function rangeListRegex(min,max){if(!Number.isInteger(min)||!Number.isInteger(max)||min>max)return null;if(min<0||max>9999)return null;if(max-min>1000)return null;const vals=[];for(let n=min;n<=max;n+=1)vals.push(String(n));const out=compressNumericValues(vals);return out?joinAlt([out]):null;}
function setListRegex(values){const nums=values.map((v)=>Number(String(v).trim())).filter((v)=>Number.isInteger(v));if(!nums.length)return null;const out=compressNumericValues(nums.map((v)=>String(v)));return out?joinAlt([out]):null;}
function compileBasicDsl(input){const s=String(input||'');let i=0,out='',usedDsl=false;while(i<s.length){const ch=s[i];if(ch==='"'){usedDsl=true;const end=s.indexOf('"',i+1);if(end<0)return{ok:false,error:'Unclosed quote in literal string.'};out+=escRegex(s.slice(i+1,end));i=end+1;continue;}if(ch==='['){usedDsl=true;const end=s.indexOf(']',i+1);if(end<0)return{ok:false,error:'Unclosed [range].'};const m=s.slice(i+1,end).trim().match(/^(-?\d+)\s*(?:-|\.\.)\s*(-?\d+)$/);if(!m)return{ok:false,error:'Range must be [min-max], e.g. [10-50].'};const rr=rangeListRegex(Number(m[1]),Number(m[2]));if(!rr)return{ok:false,error:'Invalid range span.'};out+=rr;i=end+1;continue;}if(ch==='{'){usedDsl=true;const end=s.indexOf('}',i+1);if(end<0)return{ok:false,error:'Unclosed {set}.'};const rr=setListRegex(s.slice(i+1,end).split(','));if(!rr)return{ok:false,error:'Set must be numeric list.'};out+=rr;i=end+1;continue;}out+=escRegex(ch);i+=1;}return{ok:true,out,usedDsl};}
function buildGeneralRegex(){const ws=!!$('rbWs').checked,mode=$('rbMode').value,input=String($('rbInput').value||'').trim();if(!input){status('rbStatus','Enter input text first.','warn');return;}let out='',info='';if(mode==='raw'){out=input;info='raw';}else{const compiled=compileBasicDsl(input);if(!compiled.ok){status('rbStatus','Build failed: '+compiled.error,'err');return;}out=compiled.out;info=compiled.usedDsl?'basic-dsl':'basic-literal';}out=optimizeWhitespace(out,ws);$('rbOut').value=out;status('rbStatus','Generated ('+info+'). Length: '+out.length+(hasRegexOperators(out)?' | operators detected':' | literal spacing optimized'),'ok');}
async function copyGeneralRegex(){const v=String($('rbOut').value||'');if(!v){status('rbStatus','Nothing to copy.','warn');return;}try{await navigator.clipboard.writeText(v);toast('Regex copied');status('rbStatus','Copied. Length: '+v.length,'ok');}catch(e){status('rbStatus','Clipboard write failed.','err');}}
`;
