// Auto-generated from admin-ui-src/scripts/sessions.js. Do not edit this file directly.
export const ADMIN_SESSIONS_SCRIPT = String.raw`

function safeNum(v){const n=Number(v);return Number.isFinite(n)?n:0;}
function signColor(v){const n=safeNum(v);if(n>0)return 'var(--ok)';if(n<0)return 'var(--danger)';return 'var(--muted)';}
const SESS_CFG_PERSIST_KEY='scarabev-admin-session-manager-v2';
const SESS_CFG_SESSION_KEY='scarabev-admin-session-admin-key-v1';
const SESS_CFG_PERSISTED_ADMIN_KEY='scarabev-admin-session-admin-key-persisted-v1';
const SESSION_STATE_REVIEW_PENDING='review_pending';
const L2_PASS_THRESHOLD=12;
const L2_HIGH_PRIORITY_THRESHOLD=20;
function fmtChaosRaw(v){const n=safeNum(v);return Math.round(n).toLocaleString()+'c';}
function fmtRoiPct(input,output){const i=safeNum(input),o=safeNum(output);if(i<=0)return '-';const pct=((o-i)/i)*100;return (pct>=0?'+':'')+pct.toFixed(1)+'%';}
function divFromChaos(chaos,divineRate){const rate=safeNum(divineRate);if(rate<=0)return null;return safeNum(chaos)/rate;}
function fmtDivSignedFromChaos(chaos,divineRate){const d=divFromChaos(chaos,divineRate);if(d===null)return '-';return (d>=0?'+':'')+d.toFixed(2)+' div';}
function escHtml(v){return String(v??'').replace(/[&<>"']/g,(m)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]||m));}
function parseScarabRows(s){try{const rows=JSON.parse(String(s||'[]'));return Array.isArray(rows)?rows:[];}catch(e){return[];}}
function parseReasons(v){try{const rows=JSON.parse(String(v||'[]'));if(Array.isArray(rows))return rows.map((x)=>String(x||'').trim()).filter(Boolean);}catch(e){}return [];}
function parseObj(v){try{const o=JSON.parse(String(v||'{}'));return(o&&typeof o==='object')?o:{};}catch(e){return{};}}
function stateLabel(v){const s=String(v||'').trim();if(!s)return 'legacy_approved';return s;}
function isHeldForReview(s){return stateLabel(s&&s.intake_state)===SESSION_STATE_REVIEW_PENDING;}
function fmtSignedInt(v){const n=Math.round(safeNum(v));return (n>0?'+':'')+String(n);}
function sessionRowDrift(s){const l1=parseObj(s&&s.intake_l1_json);return Math.round(safeNum(l1.drift??(s&&s.intake_drift)));}
function sessionRowNotePreview(s){const raw=String((s&&s.admin_note)||'').replace(/\s+/g,' ').trim();return raw||'-';}
function sessionRowMetrics(s){
  const l1=parseObj(s&&s.intake_l1_json);
  const l2=parseObj(s&&s.intake_l2_json);
  const input=safeNum(s&&s.input_value);
  const output=safeNum(s&&s.output_value);
  const roiPct=input>0?((output-input)/input)*100:null;
  const drift=safeNum(l1.drift??(s&&s.intake_drift));
  const driftPct=Number.isFinite(Number(l1.driftPct))?safeNum(l1.driftPct):((safeNum(l1.expectedFinal)>0)?(drift/safeNum(l1.expectedFinal))*100:null);
  const allowed=Math.max(0,safeNum(l1.allowedDrift));
  const driftRatio=allowed>0?(Math.abs(drift)/allowed):(Math.abs(drift)>0?1:0);
  const health=safeNum(s&&s.intake_health_pct);
  const l2Score=safeNum(l2.finalL2Score);
  const l1HealthLevel=health>=95?'green':(health>=85?'yellow':'red');
  const l1DriftLevel=levelByThresholds(driftRatio,0.4,0.85);
  const l2Level=l2Score>=L2_HIGH_PRIORITY_THRESHOLD?'red':(l2Score>=L2_PASS_THRESHOLD?'yellow':'green');
  return {roiPct,drift,driftPct,health,l2Score,l1HealthLevel,l1DriftLevel,l2Level};
}
function levelByThresholds(value,greenMax,yellowMax){
  const n=safeNum(value);
  if(n<=greenMax)return 'green';
  if(n<=yellowMax)return 'yellow';
  return 'red';
}
function stoplightValue(value,level){
  const txt=escHtml(String(value));
  return level?'<span class="intake-stoplight intake-'+escHtml(level)+'">'+txt+'</span>':txt;
}
function scarabsOutCount(s,l1){
  const rows=parseScarabRows(s&&s.scarabs_json);
  let total=0;
  for(const row of rows){
    total+=safeNum(row&&row.received);
  }
  return Math.round(total);
}
function openSessionCfgModal(){$('sessCfgModalWrap').classList.add('open');}
function closeSessionCfgModal(){$('sessCfgModalWrap').classList.remove('open');}
function switchSessionSubtab(tab){
  const mode=(tab==='backups'||tab==='review'||tab==='research'||tab==='analytics')?tab:'sessions';
  const paneSessions=$('sessPaneSessions'),paneBackups=$('sessPaneBackups'),paneReview=$('sessPaneReview'),paneResearch=$('sessPaneResearch'),paneAnalytics=$('sessPaneAnalytics');
  const tabSessions=$('sessTabSessions'),tabBackups=$('sessTabBackups'),tabReview=$('sessTabReview'),tabResearch=$('sessTabResearch'),tabAnalytics=$('sessTabAnalytics');
  if(paneSessions)paneSessions.classList.toggle('active',mode==='sessions');
  if(paneBackups)paneBackups.classList.toggle('active',mode==='backups');
  if(paneReview)paneReview.classList.toggle('active',mode==='review');
  if(paneResearch)paneResearch.classList.toggle('active',mode==='research');
  if(paneAnalytics)paneAnalytics.classList.toggle('active',mode==='analytics');
  if(tabSessions)tabSessions.classList.toggle('active',mode==='sessions');
  if(tabBackups)tabBackups.classList.toggle('active',mode==='backups');
  if(tabReview)tabReview.classList.toggle('active',mode==='review');
  if(tabResearch)tabResearch.classList.toggle('active',mode==='research');
  if(tabAnalytics)tabAnalytics.classList.toggle('active',mode==='analytics');
  const mobile=$('sessTabMobile'); if(mobile&&mobile.value!==mode)mobile.value=mode;
}
function syncSessionPager(total){
  const size=Math.max(1,Number(state.sessionPageSize)||25);
  const pages=Math.max(1,Math.ceil(total/size));
  state.sessionPage=Math.min(Math.max(1,Number(state.sessionPage)||1),pages);
  const start=total?((state.sessionPage-1)*size)+1:0;
  const end=Math.min(total,state.sessionPage*size);
  if($('sessPagerSummary'))$('sessPagerSummary').textContent='Showing '+start+'-'+end+' of '+total.toLocaleString();
  if($('sessPagePrev'))$('sessPagePrev').disabled=state.sessionPage<=1;
  if($('sessPageNext'))$('sessPageNext').disabled=state.sessionPage>=pages;
  return {size,pages,start,end};
}

function loadSessionCfg(){
  try{
    const raw=localStorage.getItem(SESS_CFG_PERSIST_KEY);
    const parsed=raw?JSON.parse(raw):null;
    const remember=!!(parsed&&typeof parsed==='object'&&parsed.rememberKey===true);
    state.sessionApiUrl=(parsed&&typeof parsed.apiUrl==='string')?parsed.apiUrl.trim():'';
    const sessionKey=sessionStorage.getItem(SESS_CFG_SESSION_KEY)||'';
    const persistedKey=remember?(localStorage.getItem(SESS_CFG_PERSISTED_ADMIN_KEY)||''):'';
    state.sessionAdminKey=(sessionKey||persistedKey||'').trim();
  }catch(e){}
}
function saveSessionCfg(){
  state.sessionApiUrl=($('sessApiUrl').value||'').trim();
  state.sessionAdminKey=($('sessAdminKey').value||'').trim();
  const remember=!!($('sessRememberKey')&&$('sessRememberKey').checked);
  try{
    localStorage.setItem(SESS_CFG_PERSIST_KEY,JSON.stringify({apiUrl:state.sessionApiUrl,rememberKey:remember}));
    sessionStorage.setItem(SESS_CFG_SESSION_KEY,state.sessionAdminKey);
    if(remember){
      localStorage.setItem(SESS_CFG_PERSISTED_ADMIN_KEY,state.sessionAdminKey);
    }else{
      localStorage.removeItem(SESS_CFG_PERSISTED_ADMIN_KEY);
    }
  }catch(e){}
  status('sessStatus','Session manager config saved.','ok');
  closeSessionCfgModal();
}
function hydrateSessionCfgInputs(){
  if($('sessApiUrl'))$('sessApiUrl').value=state.sessionApiUrl||'https://scarabev-api.paperpandastacks.workers.dev/admin/sessions';
  if($('sessAdminKey'))$('sessAdminKey').value=state.sessionAdminKey||'';
  if($('sessRememberKey')){
    let remember=false;
    try{
      const raw=localStorage.getItem(SESS_CFG_PERSIST_KEY);
      const parsed=raw?JSON.parse(raw):null;
      remember=!!(parsed&&typeof parsed==='object'&&parsed.rememberKey===true);
    }catch(e){}
    $('sessRememberKey').checked=remember;
  }
}
function sessionApiWithKey(pathSuffix){
  const base=($('sessApiUrl').value||state.sessionApiUrl||'').trim().replace(/\/+$/,'');
  const key=($('sessAdminKey').value||state.sessionAdminKey||'').trim();
  if(!base||!key)return null;
  const sep=pathSuffix.includes('?')?'&':'?';
  return base+pathSuffix+sep+'key='+encodeURIComponent(key);
}
function updateSessionStats(items){
  const total=items.length;
  let consumed=0,scarabsOut=0,totalProfitDiv=0,hasDivCount=0;
  for(const s of items){
    const input=safeNum(s.input_value),output=safeNum(s.output_value),profit=output-input;
    consumed+=safeNum(s.total_consumed);
    scarabsOut+=scarabsOutCount(s);
    const d=divFromChaos(profit,s.divine_rate);
    if(d!==null){
      totalProfitDiv+=Number(d.toFixed(2));
      hasDivCount+=1;
    }
  }
  $('sessMetricCount').textContent=String(total.toLocaleString());
  $('sessMetricConsumed').textContent=String(Math.round(consumed).toLocaleString());
  $('sessMetricTrades').textContent=String(Math.round(scarabsOut).toLocaleString());
  $('sessMetricProfit').textContent=hasDivCount?((totalProfitDiv>=0?'+':'')+totalProfitDiv.toFixed(2)+' div'):'-';
  $('sessMetricProfit').style.color=signColor(totalProfitDiv);
}

function buildSessionDetailHtml(s){
  const input=safeNum(s.input_value),output=safeNum(s.output_value),profit=output-input,rate=safeNum(s.divine_rate);
  const roi=fmtRoiPct(input,output);
  const l1=parseObj(s.intake_l1_json);
  const l2=parseObj(s.intake_l2_json);
  const scarabsOut=scarabsOutCount(s,l1);
  const scarabs=parseScarabRows(s.scarabs_json);
  const vendor=scarabs.filter((x)=>x&&x.was_vendor).sort((a,b)=>safeNum(b.consumed)-safeNum(a.consumed));
  const keeper=scarabs.filter((x)=>x&&!x.was_vendor&&safeNum(x.received)>0).sort((a,b)=>safeNum(b.received)-safeNum(a.received));
  const legacy=scarabs.length>0&&scarabs[0]&&scarabs[0].consumed===undefined;
  const legacyRows=scarabs.filter((x)=>x&&safeNum(x.received)>0).sort((a,b)=>safeNum(b.received)-safeNum(a.received));
  const reasons=parseReasons(s.intake_reasons_json);
  const pct=(n)=>Number.isFinite(Number(n))?(Number(n)*100).toFixed(2)+'%':'-';
  const pctSigned=(n)=>Number.isFinite(Number(n))?((Number(n)>=0?'+':'')+Number(n).toFixed(2)+'%'):'-';
  const drift=safeNum(l1.drift??s.intake_drift);
  const allowedDrift=Math.max(0,safeNum(l1.allowedDrift));
  const driftRatio=allowedDrift>0?(Math.abs(drift)/allowedDrift):(Math.abs(drift)>0?1:0);
  const healthPct=safeNum(s.intake_health_pct);
  const l1Result=String(l1.l1_result||'-');
  const l2Final=safeNum(l2.finalL2Score);
  const l2Interpretation=String(l2.interpretation||'-');
  const l1HealthLevel=healthPct>=95?'green':(healthPct>=85?'yellow':'red');
  const l1DriftLevel=levelByThresholds(driftRatio,0.4,0.85);
  const l1ResultLevel=l1Result.toLowerCase().includes('reject')?'red':'green';
  const l2SpikeLevel=levelByThresholds(l2.spikeSeverity,0.12,0.2);
  const l2ConcentrationLevel=levelByThresholds(l2.concentration,0.12,0.22);
  const l2SupportLevel=levelByThresholds(l2.supportInconsistency,0.08,0.16);
  const l2FinalLevel=l2Final>=L2_HIGH_PRIORITY_THRESHOLD?'red':(l2Final>=L2_PASS_THRESHOLD?'yellow':'green');
  const l2InterpretationLevel=l2FinalLevel;

  const rowHtml=(name,a,b,c,cColor)=>'<div class="session-scarab-row"><span title="'+escHtml(name)+'">'+escHtml(name)+'</span><span style="text-align:right">'+escHtml(String(a))+'</span><span style="text-align:right">'+escHtml(String(b))+'</span><span style="text-align:right;color:'+escHtml(cColor||'var(--muted)')+';font-weight:700">'+escHtml(String(c))+'</span></div>';
  const vendorBody=vendor.length?vendor.map((r)=>{const net=Math.round(safeNum(r.received)-safeNum(r.consumed));return rowHtml(r.name||'-',Math.round(safeNum(r.consumed)),Math.round(safeNum(r.received)),(net>=0?'+':'')+String(net),signColor(net));}).join(''):'<div class="sub">No vendor rows.</div>';
  const keeperBody=keeper.length?keeper.map((r)=>{const cea=safeNum(r.ninja_price);return rowHtml(r.name||'-','-',Math.round(safeNum(r.received)),cea>0?cea.toFixed(2)+'c':'-',cea>0?signColor(cea):'var(--muted)');}).join(''):'<div class="sub">No keeper rows.</div>';
  const legacyBody=legacyRows.length?legacyRows.map((r)=>rowHtml(r.name||'-','-',Math.round(safeNum(r.received)),'-','var(--muted)')).join(''):'<div class="sub">No scarab rows.</div>';

  return '<div class="session-detail">'
    +'<div class="session-detail-grid">'
      +'<div class="session-detail-card"><div class="lbl">Input</div><div class="val">'+fmtChaosRaw(input)+'</div></div>'
      +'<div class="session-detail-card"><div class="lbl">Output</div><div class="val">'+fmtChaosRaw(output)+'</div></div>'
      +'<div class="session-detail-card"><div class="lbl">Profit</div><div class="val" style="color:'+signColor(profit)+'">'+fmtDivSignedFromChaos(profit,rate)+'</div></div>'
      +'<div class="session-detail-card"><div class="lbl">ROI</div><div class="val" style="color:'+signColor(profit)+'">'+escHtml(roi)+'</div></div>'
    +'</div>'
    +'<div class="session-meta">'
      +'<div><b>Session ID:</b> <span class="mono">'+escHtml(String(s.id||'-'))+'</span></div>'
      +'<div><b>Date:</b> '+escHtml(formatAdminTime(s.created_at))+'</div>'
      +'<div><b>League:</b> '+escHtml(String(s.league||'-'))+'</div>'
      +'<div><b>Regex:</b> <span class="mono">'+escHtml(String(s.regex||'-'))+'</span></div>'
      +'<div><b>State:</b> '+escHtml(stateLabel(s.intake_state))+'</div>'
      +'<div><b>Scarabs In:</b> '+escHtml(String(Math.round(safeNum(s.total_consumed)).toLocaleString()))+'</div>'
      +'<div><b>Scarabs Out:</b> '+escHtml(String(scarabsOut.toLocaleString()))+'</div>'
      +'<div><b>Divine Rate:</b> '+escHtml(rate>0?rate.toFixed(2)+' c/div':'-')+'</div>'
      +'<div><b>Rows:</b> '+escHtml(String(scarabs.length))+'</div>'
      +'<div><b>L1 Structural Health:</b> '+stoplightValue(healthPct>0?Math.round(healthPct)+'%':'-',l1HealthLevel)+'</div>'
      +'<div><b>Admin Note:</b> <span class="session-detail-note">'+escHtml(String(s.admin_note||'-'))+'</span></div>'
      +'<div><b>Reasons:</b> '+escHtml(reasons.length?reasons.join(' | '):'-')+'</div>'
    +'</div>'
    +'<div class="session-meta" style="margin-top:8px">'
      +'<div><b>L1 InputQty:</b> '+escHtml(String(Math.round(safeNum(l1.inputQty??l1.totalConsumed??s.total_consumed)).toLocaleString()))+'</div>'
      +'<div><b>L1 Expected Trades:</b> '+escHtml(String(Math.round(safeNum(l1.expectedTrades??s.intake_expected_trades)).toLocaleString()))+'</div>'
      +'<div><b>L1 Leftovers:</b> '+escHtml(String(Math.round(safeNum(l1.leftovers)).toLocaleString()))+'</div>'
      +'<div><b>L1 Expected Final:</b> '+escHtml(String(Math.round(safeNum(l1.expectedFinal)).toLocaleString()))+'</div>'
      +'<div><b>L1 Actual Final:</b> '+escHtml(String(Math.round(safeNum(l1.actualFinalCount??s.intake_actual_outputs)).toLocaleString()))+'</div>'
      +'<div><b>L1 Drift:</b> '+stoplightValue(String((drift>=0?'+':'')+Math.round(drift)),l1DriftLevel)+'</div>'
      +'<div><b>L1 Drift %:</b> '+stoplightValue(pctSigned(l1.driftPct),l1DriftLevel)+'</div>'
      +'<div><b>L1 Allowed Drift:</b> '+escHtml(String(Math.round(safeNum(l1.allowedDrift)).toLocaleString()))+'</div>'
      +'<div><b>L1 Result:</b> '+stoplightValue(l1Result,l1ResultLevel)+'</div>'
      +'<div><b>L2 Spike Scarab:</b> '+escHtml(String(l2.spikeScarab||'-'))+'</div>'
      +'<div><b>L2 Expected Share:</b> '+escHtml(pct(l2.expectedShare))+'</div>'
      +'<div><b>L2 Actual Share:</b> '+escHtml(pct(l2.actualShare))+'</div>'
      +'<div><b>L2 Excess Count:</b> '+escHtml(String(safeNum(l2.excessCount).toFixed(2)))+'</div>'
      +'<div><b>L2 Mature Guard:</b> '+escHtml(String(!!l2.matureGuard))+'</div>'
      +'<div><b>L2 Excess Guard:</b> '+escHtml(String(!!l2.excessGuard))+'</div>'
      +'<div><b>L2 Spike Severity:</b> '+stoplightValue(String(safeNum(l2.spikeSeverity).toFixed(4)),l2SpikeLevel)+'</div>'
      +'<div><b>L2 MidDiv:</b> '+escHtml(String(safeNum(l2.midDiv).toFixed(4)))+'</div>'
      +'<div><b>L2 Concentration:</b> '+stoplightValue(String(safeNum(l2.concentration).toFixed(4)),l2ConcentrationLevel)+'</div>'
      +'<div><b>L2 Concentration (Adjusted):</b> '+escHtml(String(safeNum(l2.concentrationAdjusted).toFixed(4)))+'</div>'
      +'<div><b>L2 Support Inconsistency:</b> '+stoplightValue(String(safeNum(l2.supportInconsistency).toFixed(4)),l2SupportLevel)+'</div>'
      +'<div><b>L2 Support (Adjusted):</b> '+escHtml(String(safeNum(l2.supportAdjusted).toFixed(4)))+'</div>'
      +'<div><b>L2 Score Before Guards:</b> '+escHtml(String(safeNum(l2.scoreBeforeGuards).toFixed(2)))+'</div>'
      +'<div><b>L2 Score After Guards:</b> '+escHtml(String(safeNum(l2.scoreAfterGuards).toFixed(2)))+'</div>'
      +'<div><b>L2 Final Score:</b> '+stoplightValue(String(l2Final.toFixed(2)),l2FinalLevel)+'</div>'
      +'<div><b>L2 Interpretation:</b> '+stoplightValue(l2Interpretation,l2InterpretationLevel)+'</div>'
    +'</div>'
    +(legacy
      ?'<div class="session-scarab-box"><div class="session-scarab-head">Scarab Outputs (Legacy)</div>'
        +'<div class="session-scarab-row" style="font-weight:700;color:var(--heading)"><span>Name</span><span style="text-align:right">In</span><span style="text-align:right">Out</span><span style="text-align:right">C/EA</span></div>'
        +legacyBody
      +'</div>'
      :'<div class="session-scarab-split">'
        +'<div class="session-scarab-box"><div class="session-scarab-head">Vendor Scarabs</div>'
          +'<div class="session-scarab-row" style="font-weight:700;color:var(--heading)"><span>Name</span><span style="text-align:right">In</span><span style="text-align:right">Out</span><span style="text-align:right">Net</span></div>'
          +vendorBody
        +'</div>'
        +'<div class="session-scarab-box"><div class="session-scarab-head">Keeper Outputs</div>'
          +'<div class="session-scarab-row" style="font-weight:700;color:var(--heading)"><span>Name</span><span style="text-align:right">In</span><span style="text-align:right">Out</span><span style="text-align:right">C/EA</span></div>'
          +keeperBody
        +'</div>'
      +'</div>')
    +'</div>';
}

function toggleSessionDetail(id){
  const key=String(id||'');
  if(state.sessionExpandedIds.has(key))state.sessionExpandedIds.delete(key);
  else state.sessionExpandedIds.add(key);
  renderSessionRows();
}

function toggleReviewSessionDetail(id){
  const key=String(id||'');
  if(state.sessionReviewExpandedIds.has(key))state.sessionReviewExpandedIds.delete(key);
  else state.sessionReviewExpandedIds.add(key);
  renderReviewQueueRows(state.sessionReviewQueue||[]);
}

function reviewActionButtons(id){
  return '<div class="session-actions"><button class="btn mini" data-review-approve="'+escHtml(id)+'" type="button">Accept</button><button class="btn warn mini" data-review-reject="'+escHtml(id)+'" type="button">Reject</button></div>';
}
function researchActionButtons(id){
  return '<div class="session-actions"><button class="btn mini" data-research-approve="'+escHtml(id)+'" type="button">Accept</button></div>';
}
function deleteActionButton(id){
  return '<button class="btn danger mini" data-sess-id="'+escHtml(id)+'" type="button">Delete</button>';
}
function reasonsText(s){
  const reasons=parseReasons(s&&s.intake_reasons_json);
  return reasons.length?reasons.join(' | '):'-';
}
function rowActionHtml(s,mode){
  const id=String(s&&s.id||'-');
  if(mode==='review')return reviewActionButtons(id);
  if(isHeldForReview(s))return reviewActionButtons(id);
  return deleteActionButton(id);
}
function updateSessionRerunSummaryUi(){
  const n=$('sessRerunSummary');
  if(n)n.textContent=String(state.sessionLastRerunSummary||'');
}
function clearSessionRerunFeedback(){
  state.sessionRecentRerunIds=new Set();
  state.sessionRecentChangedIds=new Set();
  renderSessionRows();
}
function setSessionRerunFeedback(selectedIds,changedIds){
  const selected=Array.isArray(selectedIds)?selectedIds:[];
  const changed=Array.isArray(changedIds)?changedIds:[];
  state.sessionRecentRerunIds=new Set(selected.map((id)=>String(id||'')).filter(Boolean));
  state.sessionRecentChangedIds=new Set(changed.map((id)=>String(id||'')).filter(Boolean));
  if(window.__sessRerunFlashTimer)clearTimeout(window.__sessRerunFlashTimer);
  window.__sessRerunFlashTimer=setTimeout(()=>clearSessionRerunFeedback(),12000);
}
function syncSessionSelectionUi(rows){
  const visible=(Array.isArray(rows)?rows:[]).map((s)=>String(s&&s.id||'')).filter(Boolean);
  let selectedVisible=0;
  for(const id of visible){
    if(state.sessionSelectedIds.has(id))selectedVisible+=1;
  }
  const all=visible.length>0&&selectedVisible===visible.length;
  const partial=selectedVisible>0&&selectedVisible<visible.length;
  const box=$('sessSelectAllVisible');
  if(box){
    box.checked=all;
    box.indeterminate=partial;
    box.disabled=visible.length===0;
  }
  const btn=$('sessRerunSelectedBtn');
  if(btn){
    btn.disabled=state.sessionSelectedIds.size===0;
    btn.textContent=state.sessionSelectedIds.size>0?('Rerun Validation ('+state.sessionSelectedIds.size+')'):'Rerun Validation';
  }
}
function pruneSessionSelections(){
  const idSet=new Set((state.sessions||[]).map((s)=>String(s&&s.id||'')).filter(Boolean));
  for(const id of Array.from(state.sessionSelectedIds||[])){
    if(!idSet.has(id))state.sessionSelectedIds.delete(id);
  }
}
function setVisibleSessionSelection(checked){
  const total=state.sessions.length;
  const size=Math.max(1,Number(state.sessionPageSize)||25);
  const page=Math.max(1,Number(state.sessionPage)||1);
  const startIdx=(page-1)*size;
  const pageRows=state.sessions.slice(startIdx,startIdx+size);
  for(const s of pageRows){
    const id=String(s&&s.id||'');
    if(!id)continue;
    if(checked)state.sessionSelectedIds.add(id);
    else state.sessionSelectedIds.delete(id);
  }
  renderSessionRows();
}
function toggleSessionSelected(id,checked){
  const key=String(id||'');
  if(!key)return;
  if(checked)state.sessionSelectedIds.add(key);
  else state.sessionSelectedIds.delete(key);
}
function selectedSessionIdsAsc(){
  const byId={};
  for(const s of state.sessions||[])byId[String(s&&s.id||'')]=s;
  return Array.from(state.sessionSelectedIds||[])
    .filter((id)=>!!byId[id])
    .sort((a,b)=>{
      const sa=byId[a],sb=byId[b];
      const da=Date.parse(sa&&sa.created_at||'')||0;
      const db=Date.parse(sb&&sb.created_at||'')||0;
      if(da!==db)return da-db;
      const na=Number(a),nb=Number(b);
      if(Number.isFinite(na)&&Number.isFinite(nb))return na-nb;
      return String(a).localeCompare(String(b));
    });
}

function renderSessionTableRows(tb,items,opts){
  if(!tb)return;
  const rows=Array.isArray(items)?items:[];
  const mode=String(opts&&opts.mode||'sessions');
  const expandedIds=(opts&&opts.expandedIds)||new Set();
  const onToggle=(opts&&opts.onToggle)||(()=>{});
  tb.innerHTML='';
  if(rows.length===0){
    tb.innerHTML='<tr><td colspan="16" class="sub">'+escHtml(mode==='review'?'No sessions are currently pending review.':'No sessions to display.')+'</td></tr>';
    syncSessionSelectionUi([]);
    return;
  }
  rows.forEach((s)=>{
    const id=String(s.id||'');
    const isOpen=expandedIds.has(id);
    const held=isHeldForReview(s);
    const profit=safeNum(s.output_value)-safeNum(s.input_value);
    const m=sessionRowMetrics(s);
    const drift=sessionRowDrift(s);
    const notePreview=sessionRowNotePreview(s);
    const noteFull=String((s&&s.admin_note)||'').replace(/\s+/g,' ').trim();
    const selected=state.sessionSelectedIds.has(id);
    const rerunRecent=state.sessionRecentRerunIds&&state.sessionRecentRerunIds.has(id);
    const rerunChanged=state.sessionRecentChangedIds&&state.sessionRecentChangedIds.has(id);
    const main=document.createElement('tr');
    main.className='row session-main'+(isOpen?' open':'')+(held?' session-held':'')+(rerunRecent?' session-rerun-row':'')+(rerunChanged?' session-rerun-changed':'');
    main.innerHTML=''
      +'<td class="session-select-col"><input type="checkbox" data-sess-select="'+escHtml(id)+'"'+(selected?' checked':'')+' aria-label="Select session '+escHtml(id)+'"/></td>'
      +'<td class="mono"><span class="session-main-id"><span class="session-chev'+(isOpen?' open':'')+'">></span>'+escHtml(id)+'</span></td>'
      +'<td class="mono">'+escHtml(formatAdminTime(s.created_at))+'</td>'
      +'<td>'+escHtml(String(s.league||'-'))+'</td>'
      +'<td>'+Math.round(safeNum(s.total_consumed)).toLocaleString()+'</td>'
      +'<td>'+scarabsOutCount(s).toLocaleString()+'</td>'
      +'<td>'+fmtChaosRaw(s.input_value)+'</td>'
      +'<td>'+fmtChaosRaw(s.output_value)+'</td>'
      +'<td style="font-weight:700;color:'+signColor(profit)+'">'+fmtDivSignedFromChaos(profit,s.divine_rate)+'</td>'
      +'<td style="font-weight:700;color:'+signColor(m.roiPct)+'">'+escHtml(m.roiPct===null?'-':((m.roiPct>=0?'+':'')+m.roiPct.toFixed(1)+'%'))+'</td>'
      +'<td style="font-weight:700;color:'+signColor(drift)+'">'+escHtml(fmtSignedInt(drift))+'</td>'
      +'<td>'+stoplightValue(m.driftPct===null?'-':((m.driftPct>=0?'+':'')+m.driftPct.toFixed(2)+'%'),m.l1DriftLevel)+'</td>'
      +'<td>'+stoplightValue(m.health>0?(Math.round(m.health)+'%'):'-',m.l1HealthLevel)+'</td>'
      +'<td>'+stoplightValue(m.l2Score.toFixed(2),m.l2Level)+'</td>'
      +'<td class="session-note-cell" title="'+escHtml(noteFull||'-')+'"><span class="session-note-text">'+escHtml(notePreview)+'</span></td>'
      +'<td>'+rowActionHtml(s,mode)+'</td>';
    main.onclick=(ev)=>{if(ev.target&&(/BUTTON|INPUT|LABEL/.test(ev.target.tagName)))return;onToggle(id);};
    tb.appendChild(main);

    const detail=document.createElement('tr');
    detail.className='session-detail-row'+(isOpen?'':' hidden')+(held?' session-held-detail':'');
    detail.innerHTML='<td colspan="16">'+buildSessionDetailHtml(s)+'</td>';
    tb.appendChild(detail);
  });
  tb.querySelectorAll('input[data-sess-select]').forEach((box)=>{
    box.onclick=(ev)=>ev.stopPropagation();
    box.onchange=(ev)=>{
      const id=box.dataset.sessSelect||'';
      toggleSessionSelected(id,!!box.checked);
      syncSessionSelectionUi(rows);
    };
  });
  tb.querySelectorAll('button[data-sess-id]').forEach((btn)=>{btn.onclick=(ev)=>{ev.stopPropagation();deleteSessionRow(btn.dataset.sessId,btn);};});
  tb.querySelectorAll('button[data-review-approve]').forEach((btn)=>{btn.onclick=(ev)=>{ev.stopPropagation();runSessionReviewAction(btn.dataset.reviewApprove,'approve',btn);};});
  tb.querySelectorAll('button[data-review-reject]').forEach((btn)=>{btn.onclick=(ev)=>{ev.stopPropagation();runSessionReviewAction(btn.dataset.reviewReject,'reject',btn);};});
  syncSessionSelectionUi(rows);
}

function renderSessionRows(){
  const tb=$('sessRows');
  if(!tb)return;
  updateSessionRerunSummaryUi();
  const total=state.sessions.length;
  const pager=syncSessionPager(total);
  const startIdx=(state.sessionPage-1)*pager.size;
  const pageRows=state.sessions.slice(startIdx,startIdx+pager.size);
  renderSessionTableRows(tb,pageRows,{mode:'sessions',expandedIds:state.sessionExpandedIds,onToggle:toggleSessionDetail});
}

async function loadSessionsManager(opts){
  const quiet=!!(opts&&opts.quiet);
  const url=sessionApiWithKey('?limit=500');
  if(!url){if(!quiet)status('sessStatus','Set session API URL and admin key first.','warn');return false;}
  busy('sessLoadBtn',true);
  try{
    const r=await fetch(url,{method:'GET'});
    const txt=await r.text();
    if(!r.ok){if(!quiet)status('sessStatus','Load sessions failed ('+formatApiFailure(r,null,txt)+').','err');return false;}
    let data=null;try{data=JSON.parse(txt);}catch(e){}
    if(!Array.isArray(data)){if(!quiet)status('sessStatus','Unexpected session payload format.','err');return false;}
    state.sessions=data;
    pruneSessionSelections();
    state.sessionPage=1;
    if($('sessPageSize'))$('sessPageSize').value=String(state.sessionPageSize||25);
    state.sessionExpandedIds=new Set();
    state.sessionsAutoLoaded=true;
    updateSessionStats(state.sessions);
    renderSessionRows();
    if(!quiet)status('sessStatus','Loaded '+state.sessions.length+' session(s). Click a row to expand details.','ok');
    return true;
  }catch(e){
    if(!quiet)status('sessStatus','Session fetch error: '+formatThrownError(e),'err');
    return false;
  }finally{
    busy('sessLoadBtn',false);
  }
}

async function recomputeAggregate(){
  const base=($('sessApiUrl').value||state.sessionApiUrl||'').trim().replace(/\/admin\/sessions\/?$/,'');
  if(!base){status('sessStatus','Set session API URL first.','warn');return;}
  busy('sessRecomputeBtn',true);
  try{
    const r=await fetch(base+'/api/aggregate?recompute=1');
    const txt=await r.text();
    if(!r.ok){status('sessStatus','Recompute failed ('+formatApiFailure(r,null,txt)+').','err');return;}
    status('sessStatus','Aggregate recompute triggered.','ok');
  }catch(e){
    status('sessStatus','Recompute error: '+formatThrownError(e),'err');
  }finally{
    busy('sessRecomputeBtn',false);
  }
}

async function rerunSelectedSessionsIntake(){
  const base=($('sessApiUrl').value||state.sessionApiUrl||'').trim().replace(/\/+$/,'');
  const key=($('sessAdminKey').value||state.sessionAdminKey||'').trim();
  if(!base||!key){status('sessStatus','Set session API URL and admin key first.','warn');return;}
  const ids=selectedSessionIdsAsc();
  if(ids.length===0){status('sessStatus','Select at least one session first.','warn');return;}
  if(!confirm('Rerun intake L1/L2 on '+ids.length+' selected session(s)? This can change hold/pass outcomes based on current logic. Continue?'))return;
  busy('sessRerunSelectedBtn',true);
  try{
    const url=base+'/rerun-intake?key='+encodeURIComponent(key);
    const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({ids})});
    const txt=await r.text();
    let data=null;try{data=JSON.parse(txt);}catch(e){}
    if(!r.ok){
      status('sessStatus','Selected rerun failed ('+formatApiFailure(r,data,txt)+').','err');
      return;
    }
    const selected=safeNum(data&&data.selected);
    const updated=safeNum(data&&data.updated);
    const processed=safeNum(data&&data.processed);
    const skipped=safeNum(data&&data.skipped);
    const errors=safeNum(data&&data.errors);
    const changed=safeNum(data&&data.changed);
    const changedIds=Array.isArray(data&&data.changedIds)?data.changedIds.map((x)=>String(x||'')).filter(Boolean):[];
    const counts=(data&&data.stateCounts&&typeof data.stateCounts==='object')?data.stateCounts:{};
    state.sessionSelectedIds=new Set();
    setSessionRerunFeedback(ids,changedIds);
    state.sessionLastRerunSummary='Last rerun: '+new Date().toLocaleTimeString()+' | selected='+selected+', changed='+changed+', errors='+errors;
    updateSessionRerunSummaryUi();
    status('sessStatus','Selected rerun complete. selected='+selected+', processed='+processed+', updated='+updated+', changed='+changed+', skipped='+skipped+', errors='+errors+' | approved_auto='+(safeNum(counts.approved_auto)||0)+', review_pending='+(safeNum(counts.review_pending)||0)+', l1_reject='+(safeNum(counts.l1_reject)||0)+'.','ok');
    toast('Rerun complete: '+selected+' selected, '+changed+' changed');
    await Promise.all([loadSessionsManager({quiet:true}),loadReviewQueue({quiet:true}),loadResearchPile({quiet:true}),loadIntakeAnalytics({quiet:true})]);
    renderSessionRows();
  }catch(e){
    status('sessStatus','Selected rerun error: '+formatThrownError(e),'err');
  }finally{
    busy('sessRerunSelectedBtn',false);
  }
}

async function deleteSessionRow(id,btn){
  if(!id){toast('Missing session id');return;}
  if(!confirm('Delete session '+id+' from aggregated data?'))return;
  const base=($('sessApiUrl').value||state.sessionApiUrl||'').trim().replace(/\/+$/,'');
  const key=($('sessAdminKey').value||state.sessionAdminKey||'').trim();
  if(!base||!key){status('sessStatus','Missing API URL or admin key.','warn');return;}
  btn.disabled=true;const prev=btn.textContent;btn.textContent='Working...';
  try{
    const r=await fetch(base+'/'+encodeURIComponent(id)+'?key='+encodeURIComponent(key),{method:'DELETE'});
    const txt=await r.text();
    if(!r.ok){status('sessStatus','Delete failed ('+formatApiFailure(r,null,txt)+').','err');return;}
    state.sessions=state.sessions.filter((x)=>String(x.id)!==String(id));
    state.sessionExpandedIds.delete(String(id));
    updateSessionStats(state.sessions);
    renderSessionRows();
    await recomputeAggregate();
    await loadIntakeAnalytics({quiet:true});
    toast('Session deleted');
  }catch(e){
    status('sessStatus','Delete error: '+formatThrownError(e),'err');
  }finally{
    btn.disabled=false;btn.textContent=prev;
  }
}

function renderReviewQueueRows(items){
  const tb=$('sessReviewRows');
  renderSessionTableRows(tb,items,{mode:'review',expandedIds:state.sessionReviewExpandedIds,onToggle:toggleReviewSessionDetail});
}

function renderResearchRows(items){
  const tb=$('sessResearchRows');
  if(!tb)return;
  tb.innerHTML='';
  if(!Array.isArray(items)||items.length===0){
    tb.innerHTML='<tr><td colspan="10" class="sub">Research pile is empty.</td></tr>';
    return;
  }
  items.forEach((s)=>{
    const id=String(s.id||'-');
    const tr=document.createElement('tr');
    tr.className='row';
    tr.innerHTML=''
      +'<td class="mono">'+escHtml(id)+'</td>'
      +'<td class="mono">'+escHtml(formatAdminTime(s.created_at))+'</td>'
      +'<td>'+escHtml(String(s.league||'-'))+'</td>'
      +'<td>'+escHtml(String(Math.round(safeNum(s.total_consumed)).toLocaleString()))+'</td>'
      +'<td>'+escHtml(String(scarabsOutCount(s).toLocaleString()))+'</td>'
      +'<td>'+escHtml(fmtChaosRaw(s.input_value))+'</td>'
      +'<td>'+escHtml(fmtChaosRaw(s.output_value))+'</td>'
      +'<td>'+escHtml(stateLabel(s.intake_state))+'</td>'
      +'<td title="'+escHtml(reasonsText(s))+'">'+escHtml(reasonsText(s))+'</td>'
      +'<td>'+researchActionButtons(id)+'</td>';
    tb.appendChild(tr);
  });
  tb.querySelectorAll('button[data-research-approve]').forEach((btn)=>{btn.onclick=()=>runSessionReviewAction(btn.dataset.researchApprove,'approve',btn);});
}

async function loadReviewQueue(opts){
  const quiet=!!(opts&&opts.quiet);
  const url=sessionApiWithKey('/review?limit=200');
  if(!url){if(!quiet)status('sessReviewStatus','Set session API URL and admin key first.','warn');return false;}
  if($('sessReviewRefreshBtn'))busy('sessReviewRefreshBtn',true);
  try{
    const r=await fetch(url,{method:'GET'});
    const txt=await r.text();
    if(!r.ok){if(!quiet)status('sessReviewStatus','Review queue load failed ('+formatApiFailure(r,null,txt)+').','err');return false;}
    let data=null;try{data=JSON.parse(txt);}catch(e){}
    if(!Array.isArray(data)){if(!quiet)status('sessReviewStatus','Unexpected review queue payload format.','err');return false;}
    state.sessionReviewQueue=data;
    state.sessionReviewExpandedIds=new Set((state.sessionReviewExpandedIds||new Set()).size?Array.from(state.sessionReviewExpandedIds).filter((id)=>data.some((x)=>String(x&&x.id||'')===String(id))):[]);
    renderReviewQueueRows(data);
    if(!quiet)status('sessReviewStatus','Loaded '+data.length+' review session(s).','ok');
    return true;
  }catch(e){
    if(!quiet)status('sessReviewStatus','Review queue fetch error: '+formatThrownError(e),'err');
    return false;
  }finally{
    if($('sessReviewRefreshBtn'))busy('sessReviewRefreshBtn',false);
  }
}

async function loadResearchPile(opts){
  const quiet=!!(opts&&opts.quiet);
  const url=sessionApiWithKey('/research?limit=200');
  if(!url){if(!quiet)status('sessResearchStatus','Set session API URL and admin key first.','warn');return false;}
  if($('sessResearchRefreshBtn'))busy('sessResearchRefreshBtn',true);
  try{
    const r=await fetch(url,{method:'GET'});
    const txt=await r.text();
    if(!r.ok){if(!quiet)status('sessResearchStatus','Research pile load failed ('+formatApiFailure(r,null,txt)+').','err');return false;}
    let data=null;try{data=JSON.parse(txt);}catch(e){}
    if(!Array.isArray(data)){if(!quiet)status('sessResearchStatus','Unexpected research payload format.','err');return false;}
    state.sessionResearchPile=data;
    renderResearchRows(data);
    if(!quiet)status('sessResearchStatus','Loaded '+data.length+' research session(s).','ok');
    return true;
  }catch(e){
    if(!quiet)status('sessResearchStatus','Research pile fetch error: '+formatThrownError(e),'err');
    return false;
  }finally{
    if($('sessResearchRefreshBtn'))busy('sessResearchRefreshBtn',false);
  }
}

function fmtPctPart(count,total){
  const c=safeNum(count),t=safeNum(total);
  if(t<=0)return '0.0%';
  return ((c/t)*100).toFixed(1)+'%';
}

function renderIntakeAnalytics(payload){
  const data=(payload&&typeof payload==='object')?payload:{};
  const total=Math.max(0,Math.round(safeNum(data.totalSubmissions)));
  const scoreCount=Math.max(0,Math.round(safeNum(data.l2ScoreCount)));
  const avg=safeNum(data.averageL2Score);
  const med=safeNum(data.medianL2Score);
  if($('sessAnalyticsTotal'))$('sessAnalyticsTotal').textContent=total.toLocaleString();
  if($('sessAnalyticsAvgL2'))$('sessAnalyticsAvgL2').textContent=scoreCount?avg.toFixed(2):'-';
  if($('sessAnalyticsMedianL2'))$('sessAnalyticsMedianL2').textContent=scoreCount?med.toFixed(2):'-';
  if($('sessAnalyticsScoreCount'))$('sessAnalyticsScoreCount').textContent=scoreCount.toLocaleString();

  const counts=(data.counts&&typeof data.counts==='object')?data.counts:{};
  const rows=[
    ['approved_auto',safeNum(counts.approved_auto)],
    ['review_pending',safeNum(counts.review_pending)],
    ['approved_manual',safeNum(counts.approved_manual)],
    ['research',safeNum(counts.research)],
    ['l1_reject',safeNum(data.l1RejectCount)],
    ['l1_reject_duplicate_submission',safeNum(data.duplicateSubmissionCount)]
  ];
  const stateTb=$('sessAnalyticsStateRows');
  if(stateTb){
    stateTb.innerHTML='';
    rows.forEach((r)=>{
      const tr=document.createElement('tr');
      tr.innerHTML=''
        +'<td>'+escHtml(r[0])+'</td>'
        +'<td>'+escHtml(String(Math.round(r[1]).toLocaleString()))+'</td>'
        +'<td>'+escHtml(fmtPctPart(r[1],total))+'</td>';
      stateTb.appendChild(tr);
    });
  }

  const hist=(data.scoreHistogram&&typeof data.scoreHistogram==='object')?data.scoreHistogram:{};
  const histRows=[
    ['<12',safeNum(hist.lt12)],
    ['12-20',safeNum(hist.b12to20)],
    ['20-35',safeNum(hist.b20to35)],
    ['35+',safeNum(hist.gte35)]
  ];
  const histTb=$('sessAnalyticsHistRows');
  if(histTb){
    histTb.innerHTML='';
    histRows.forEach((r)=>{
      const tr=document.createElement('tr');
      tr.innerHTML=''
        +'<td>'+escHtml(r[0])+'</td>'
        +'<td>'+escHtml(String(Math.round(r[1]).toLocaleString()))+'</td>'
        +'<td>'+escHtml(fmtPctPart(r[1],scoreCount))+'</td>';
      histTb.appendChild(tr);
    });
  }
}

async function loadIntakeAnalytics(opts){
  const quiet=!!(opts&&opts.quiet);
  const url=sessionApiWithKey('/analytics');
  if(!url){if(!quiet)status('sessAnalyticsStatus','Set session API URL and admin key first.','warn');return false;}
  if($('sessAnalyticsRefreshBtn'))busy('sessAnalyticsRefreshBtn',true);
  try{
    const r=await fetch(url,{method:'GET'});
    const txt=await r.text();
    if(!r.ok){if(!quiet)status('sessAnalyticsStatus','Analytics load failed ('+formatApiFailure(r,null,txt)+').','err');return false;}
    let data=null;try{data=JSON.parse(txt);}catch(e){}
    if(!data||typeof data!=='object'){if(!quiet)status('sessAnalyticsStatus','Unexpected analytics payload format.','err');return false;}
    state.sessionIntakeAnalytics=data;
    renderIntakeAnalytics(data);
    if(!quiet)status('sessAnalyticsStatus','Loaded intake analytics snapshot.','ok');
    return true;
  }catch(e){
    if(!quiet)status('sessAnalyticsStatus','Analytics fetch error: '+formatThrownError(e),'err');
    return false;
  }finally{
    if($('sessAnalyticsRefreshBtn'))busy('sessAnalyticsRefreshBtn',false);
  }
}

function promptDecisionNote(action,id){
  const text=prompt((action==='approve'?'Accept ':'Reject ')+'session '+id+'. Optional admin note:','');
  if(text===null)return null;
  return String(text||'').trim();
}

async function runSessionReviewAction(id,action,btn){
  if(!id||!(action==='approve'||action==='reject'))return;
  const note=promptDecisionNote(action,id);
  if(note===null)return;
  const base=($('sessApiUrl').value||state.sessionApiUrl||'').trim().replace(/\/+$/,'');
  const key=($('sessAdminKey').value||state.sessionAdminKey||'').trim();
  if(!base||!key){status('sessStatus','Missing API URL or admin key.','warn');return;}
  if(btn){btn.disabled=true;}
  try{
    const url=base+'/'+encodeURIComponent(id)+'/'+action+'?key='+encodeURIComponent(key);
    const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({note})});
    const txt=await r.text();
    if(!r.ok){
      status('sessStatus',(action==='approve'?'Accept':'Reject')+' failed ('+formatApiFailure(r,null,txt)+').','err');
      return;
    }
    status('sessStatus','Session '+id+' '+(action==='approve'?'accepted':'moved to research')+'.','ok');
    await Promise.all([loadSessionsManager({quiet:true}),loadReviewQueue({quiet:true}),loadResearchPile({quiet:true}),loadIntakeAnalytics({quiet:true})]);
  }catch(e){
    status('sessStatus',(action==='approve'?'Accept':'Reject')+' error: '+formatThrownError(e),'err');
  }finally{
    if(btn){btn.disabled=false;}
  }
}

`;
