export const ADMIN_TOKENS_SCRIPT = String.raw`
function renderTokenSetRows(){const selected=$('rbId').value.trim();const tb=$('setRows');tb.innerHTML='';for(const x of state.sets){const tr=document.createElement('tr');tr.className='row'+(selected===x.id?' sel':'');tr.innerHTML='<td class="mono">'+x.id+'</td><td>'+x.state+'</td><td class="mono">'+formatAdminTime(x.createdAt)+'</td><td>'+(x.entries?x.entries.length:0)+'</td>';tr.onclick=()=>{$('rbId').value=x.id;renderTokenSetRows();};tb.appendChild(tr);}}
async function loadTokens(){const p=await api('/public/token-set/latest');if(p.res.status===200&&p.json?.tokensByName){state.tokensByName=p.json.tokensByName;$('pubVer').textContent=p.json.versionId||'-';$('pubCount').textContent=String(p.json.itemCount||0);}else{state.tokensByName={};$('pubVer').textContent='-';$('pubCount').textContent='-';}const latestDraft=await api('/admin/token-drafts/latest');state.draftTokensByScarabId={};state.latestDraftEntries=[];if(latestDraft.res.status===200&&latestDraft.json?.draft?.entries){state.latestDraftEntries=latestDraft.json.draft.entries||[];for(const e of state.latestDraftEntries){state.draftTokensByScarabId[e.scarabId]=e.token;}}const s=await api('/admin/token-sets?limit=20');if(s.res.status===200&&s.json){state.tokensAutoLoaded=true;state.sets=s.json.items||[];renderTokenSetRows();status('tokStatus','Loaded token set history: '+state.sets.length+' set(s). Published set size: '+$('pubCount').textContent+'.','ok');}else{status('tokStatus','Token set load failed ('+s.res.status+').','err');}}
async function loadAll(){await loadScarabs();await loadTokens();}
function buildRegexPair(){const ordered=(state.scarabs||[]).filter((s)=>s.status==='active').map((s)=>state.draftTokensByScarabId[s.id]).filter(Boolean);const fallback=state.latestDraftEntries.map((e)=>e.token).filter(Boolean);const toks=(ordered.length?ordered:fallback);if(!toks.length){status('regexStatus','No draft entries available. Generate a draft first.','warn');$('regex1').value='';$('regex2').value='';return;}const maxLen=250;const built=['',''];let idx=0;for(const tok of toks){const part=escRegex(tok);const add=(built[idx]?built[idx]+'|'+part:part);if(add.length<=maxLen){built[idx]=add;continue;}if(idx===0){idx=1;const add2=(built[idx]?built[idx]+'|'+part:part);if(add2.length<=maxLen){built[idx]=add2;continue;}}status('regexStatus','Could not fit tokens into two 250-char regex strings.','err');return;}$('regex1').value=built[0];$('regex2').value=built[1];status('regexStatus','Built regex pair. Regex1 len: '+built[0].length+' | Regex2 len: '+built[1].length,(built[1]?'ok':'warn'));}
async function gen(){busy('genBtn',true);if($('genActiveBtn'))busy('genActiveBtn',true);try{const sc=activeScope();const active=activeProfile();const r=await api('/admin/token-drafts/generate',{method:'POST',body:JSON.stringify({seasonId:sc.seasonId||null,orderBy:'created'})});if(r.res.status!==201||!r.json){status('tokStatus','Generate failed ('+r.res.status+').','err');toast('Generate failed');return;}await loadTokens();buildRegexPair();toast('Draft generated');status('tokStatus','Draft generated for active workspace '+(active?active.name:'-')+' ('+(active?active.seasonId:'-')+').','ok');}finally{busy('genBtn',false);if($('genActiveBtn'))busy('genActiveBtn',false);}}
function formatPublishGateFailure(payload){
  const gate=payload?.gate||{};
  const parts=[];
  if(gate.hasUnresolvedCollisions){parts.push('Unresolved token collisions');}
  if(Array.isArray(gate.missingCoverage)&&gate.missingCoverage.length){parts.push('Missing coverage for '+gate.missingCoverage.length+' active scarab(s)');}
  if(Array.isArray(gate.regexViolations)&&gate.regexViolations.length){parts.push('Regex profile violations: '+gate.regexViolations.length);}
  if(!parts.length){return null;}
  const extra=[];
  if(Array.isArray(gate.missingCoverage)&&gate.missingCoverage.length){
    extra.push('Missing IDs: '+gate.missingCoverage.slice(0,8).join(', ')+(gate.missingCoverage.length>8?' ...':''));
  }
  return parts.join(' | ')+(extra.length?('\\n'+extra.join('\\n')):'');
}
async function publish(){busy('pubBtn',true);if($('publishActiveBtn'))busy('publishActiveBtn',true);try{const active=activeProfile();const r=await api('/admin/token-sets/publish',{method:'POST',body:'{}'});if(r.res.status!==201||!r.json){if(r.res.status===409&&r.json?.error==='publish_gate_failed'){const detail=formatPublishGateFailure(r.json);status('tokStatus','Publish blocked by gate checks.'+(detail?('\\n'+detail):''),'warn');toast('Publish blocked');}else{status('tokStatus','Publish failed ('+r.res.status+').','err');}return;}status('tokStatus','Published '+r.json.tokenSet.id+' from active workspace '+(active?active.name:'-')+'.','ok');toast('Published to frontend token endpoint');await loadAll();}finally{busy('pubBtn',false);if($('publishActiveBtn'))busy('publishActiveBtn',false);}}
async function rollback(){const id=$('rbId').value.trim();if(!id){status('tokStatus','Enter token set id.','warn');return;}busy('rbBtn',true);try{const r=await api('/admin/token-sets/'+encodeURIComponent(id)+'/activate',{method:'POST',body:'{}'});if(r.res.status!==200||!r.json){status('tokStatus','Rollback failed ('+r.res.status+').','err');return;}status('tokStatus','Rollback to '+r.json.tokenSet.id,'ok');toast('Rollback complete');await loadAll();}finally{busy('rbBtn',false);}}
async function deleteTokenSet(){const id=$('rbId').value.trim();if(!id){status('tokStatus','Select or enter a token set id first.','warn');return;}if(!confirm('Delete token set '+id+'? This cannot be undone.'))return;const typed=prompt('Type confirm to permanently delete this token set.');if(typed===null)return;if(typed.trim().toLowerCase()!=='confirm'){status('tokStatus','Delete cancelled: confirmation text did not match.','warn');return;}busy('deleteSetBtn',true);try{const r=await api('/admin/token-sets/'+encodeURIComponent(id),{method:'DELETE'});if(r.res.status===409&&r.json?.error==='published_blocked'){status('tokStatus','Cannot delete the currently published token set. Roll back/publish another set first.','warn');return;}if(r.res.status!==200||!r.json){status('tokStatus','Delete set failed ('+r.res.status+').','err');return;}status('tokStatus','Deleted token set '+id+'.','ok');toast('Token set deleted');if($('rbId').value.trim()===id)$('rbId').value='';await loadTokens();}finally{busy('deleteSetBtn',false);}}
`;
