export const ADMIN_WIRE_SCRIPT = String.raw`
function wire(){
  const loadSessionsAndIntel=async(opts)=>{const ok=await loadSessionsManager(opts);if(ok&&typeof refreshSessionIntel==='function')refreshSessionIntel({quiet:!!(opts&&opts.quiet)});return ok;};
  $('themeBtn').onclick=toggleTheme; $('signoutBtn').onclick=logout; $('loginBtn').onclick=login;
  $('navScarab').onclick=async()=>{switchPanel('scarab');if(!state.scarabsAutoLoaded)await loadScarabs();await loadTokens();}; $('navSessions').onclick=async()=>{switchPanel('sessions');if(!state.sessionsAutoLoaded)await loadSessionsAndIntel({quiet:true});if(!state.backupsAutoLoaded)await opsListBackups({quiet:true});}; $('navHealth').onclick=async()=>{switchPanel('health');if(!state.healthAutoLoaded)await loadHealthOverview({quiet:true});}; $('navRegex').onclick=()=>switchPanel('regex');
  $('scarabTabList').onclick=()=>switchScarabSubtab('list'); $('scarabTabRestore').onclick=async()=>{switchScarabSubtab('restore');await loadTokens();}; $('scarabTabRegex').onclick=async()=>{switchScarabSubtab('regex');if(!state.tokensAutoLoaded)await loadTokens();};
  $('sessOpenCfgBtn').onclick=openSessionCfgModal; $('sessCfgCloseBtn').onclick=closeSessionCfgModal; $('sessSaveCfgBtn').onclick=saveSessionCfg; $('sessLoadBtn').onclick=()=>loadSessionsAndIntel(); $('sessRecomputeBtn').onclick=recomputeAggregate; $('sessTabSessions').onclick=()=>switchSessionSubtab('sessions'); $('sessTabBackups').onclick=async()=>{switchSessionSubtab('backups');if(!state.backupsAutoLoaded)await opsListBackups({quiet:true});}; $('sessTabDupes').onclick=()=>{switchSessionSubtab('dupes');refreshSessionIntel({quiet:true});}; $('sessTabSignals').onclick=()=>{switchSessionSubtab('signals');refreshSessionIntel({quiet:true});}; $('sessDupesRefreshBtn').onclick=()=>refreshSessionIntel(); $('sessSignalsRefreshBtn').onclick=()=>refreshSessionIntel(); $('sessPageSize').onchange=()=>{state.sessionPageSize=Number($('sessPageSize').value)||25;state.sessionPage=1;renderSessionRows();}; $('sessPagePrev').onclick=()=>{state.sessionPage=Math.max(1,(Number(state.sessionPage)||1)-1);renderSessionRows();}; $('sessPageNext').onclick=()=>{state.sessionPage=(Number(state.sessionPage)||1)+1;renderSessionRows();};
  $('refreshBtn').onclick=loadAll; $('addBtn').onclick=openEditorCreate; $('importBtn').onclick=()=>$('importFile').click(); $('importFile').onchange=async()=>{const file=$('importFile').files&&$('importFile').files[0];await importFromJsonFile(file);$('importFile').value='';};
  $('captureToolBtn').onclick=openCaptureModal; $('captureCloseBtn').onclick=closeCaptureModal; $('captureFromClipboardBtn').onclick=captureFromClipboard; $('captureExportBtn').onclick=exportCaptureQueue; $('captureImportBtn').onclick=importCaptureQueue; $('captureClearBtn').onclick=clearCaptureQueue;
  $('retireSelectedBtn').onclick=bulkRetire; $('deleteSelectedBtn').onclick=bulkDelete;
  $('genActiveBtn').onclick=gen; $('publishActiveBtn').onclick=publish;
  $('q').oninput=filterScarabs; $('sf').onchange=filterScarabs; $('sortBy').onchange=()=>{state.sortBy=$('sortBy').value;filterScarabs();}; $('selectAll').onchange=()=>{const checked=$('selectAll').checked;for(const s of state.filtered){if(checked)state.selectedIds.add(s.id);else state.selectedIds.delete(s.id);}renderRows();};
  $('editorCloseBtn').onclick=closeModal; $('parseBtn').onclick=parseIntoForm; $('clearPasteBtn').onclick=()=>{$('paste').value='';status('pasteStatus','Cleared.','ok');}; $('saveBtn').onclick=saveEditor; $('retireBtn').onclick=retireCurrent; $('deleteBtn').onclick=deleteCurrent;
  $('tokRefreshBtn').onclick=loadTokens; $('buildRegexBtn').onclick=buildRegexPair; $('rbBtn').onclick=rollback; $('deleteSetBtn').onclick=deleteTokenSet; $('rbId').oninput=()=>renderTokenSetRows();
  $('rbBuildBtn').onclick=buildGeneralRegex; $('rbCopyBtn').onclick=copyGeneralRegex;
  $('opsListBtn').onclick=()=>opsListBackups(); $('opsRunBtn').onclick=opsRunBackup;
  $('healthRefreshBtn').onclick=()=>loadHealthOverview();
  $('editorModalWrap').addEventListener('click',(ev)=>{if(ev.target.id==='editorModalWrap')closeModal();}); $('captureModalWrap').addEventListener('click',(ev)=>{if(ev.target.id==='captureModalWrap')closeCaptureModal();}); $('sessCfgModalWrap').addEventListener('click',(ev)=>{if(ev.target.id==='sessCfgModalWrap')closeSessionCfgModal();});
}
(async function init(){initTheme();loadSessionCfg();wire();hydrateSessionCfgInputs();switchScarabSubtab('list');switchSessionSubtab('sessions');initCaptureQueue();switchPanel('health');state.user=null;setAuthUi(false);$('authStatus').classList.add('hidden');$('retireSelectedBtn').disabled=true;$('deleteSelectedBtn').disabled=true;try{await api('/admin/auth/logout',{method:'POST',body:'{}'});}catch(e){}})();
`;
